[package]
name = "ray_tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17"
crossbeam = "0.8"
nanorand = "0.6"
glam = "0.20"
log = "0.4"
env_logger = "0.9"
